import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {exportHTML} from './export-built.mjs';
const seed=JSON.parse(fs.readFileSync('src/initial.json')),plan=structuredClone(seed);plan.schedule[2][5][5]='<img src=x onerror=alert(1)> · Õpetaja';plan.title='Test </script><script>alert(1)</script>';
const html=exportHTML(plan),data=html.match(/<script type="application\/json" id="plan-data">([\s\S]*?)<\/script>/)[1];assert.deepEqual(JSON.parse(data),plan);assert(!data.includes('</script>'));
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,2);const code=scripts[1][1];new vm.Script(code);new vm.Script(fs.readFileSync('dist/uuenda.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1]);
const elems={};let utc='2026-09-09T10:33:00Z';class Clock extends Date{constructor(...x){super(...(x.length?x:[utc]))}static now(){return new Date(utc).getTime()}}
const el=id=>elems[id]??={value:id==='class'?'5':'',textContent:id==='plan-data'?data:'',style:{},add(){},setAttribute(){},querySelectorAll(){return []},querySelector(){return null}};
const ctx={document:{getElementById:el,addEventListener(){}},window:{addEventListener(){}},Option:function(){},Intl,Date:Clock,Number,Array,Object,String,Uint8Array,Blob,URL,atob,setInterval(){},requestAnimationFrame:fn=>fn()};vm.createContext(ctx);vm.runInContext(code,ctx);el('week').onclick();assert.equal((el('table').innerHTML.match(/current-slot/g)||[]).length,1);assert(!el('table').innerHTML.includes('<img'));assert(el('table').innerHTML.includes('&lt;img'));assert.equal(el('plan-name').textContent,plan.title);assert.equal(Buffer.from(JSON.parse(data).pdfBase64,'base64').subarray(0,5).toString(),'%PDF-');
assert.throws(()=>exportHTML({...plan,schedule:[]}));assert.throws(()=>exportHTML({...plan,pdfBase64:'<script>'}));
console.log('PASS: export/import data round trip, embedded PDF, safe text, preserved timetable, week highlight and script syntax.');
